### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brutalhonesty** [taterbase/node-keybase#2]
Hey there,

Looking to find out what the license is your source code in this repo.

Would be helpful in the package.json file, a LICENSE file, as well as mentioning it in the README!

Thanks! :+1:

**Comment by taterbase** [comment]
My bad, this is ISC (very similar to MIT) I'll update it right away.

**Comment by taterbase** [comment]
Added here now: https://github.com/taterbase/node-keybase/blob/master/LICENSE.md
